services:
  immich-mobile:
    build:
      dockerfile: Dockerfile
    hostname: immich-devcontainer-mobile
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      # by default, bind mount host to /workspaces/immich
      - ../..:/workspaces/immich
      - ./vscode:/workspaces/immich/.vscode
      - cli_node_modules:/workspaces/immich/cli/node_modules
      - e2e_node_modules:/workspaces/immich/e2e/node_modules
      - open_api_node_modules:/workspaces/immich/open-api/typescript-sdk/node_modules
      - server_node_modules:/workspaces/immich/server/node_modules
      - web_node_modules:/workspaces/immich/web/node_modules
      - ${UPLOAD_LOCATION}:/workspaces/immich/server/upload

volumes:
  cli_node_modules:
  e2e_node_modules:
  open_api_node_modules:
  server_node_modules:
  web_node_modules:
  immich:
  upload-volume:
  db-volume:
