services:
  immich-mobile:
    build:
      dockerfile: Dockerfile
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ../..:/immich
      - open_api_node_modules:/immich/open-api/typescript-sdk/node_modules
